name: Text iOS Project
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test_project:
        name: Testing iOS Project
        runs-on: macos-latest
        steps:
            - name: Checkout to main
              uses: actions/checkout@v7
            
            - name: Install XCBeautify and SwiftLint
              run: brew install xcbeautify swiftlint
              
            - name: Lint
              run: swiftlint lint
              
            - name: Show project info
              run: |
                xcodebuild -version
                xcodebuild -project GHActions.xcodeproj -list
