name: Test iOS Project
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test_project:
        name: Testing iOS Project
        runs-on: macos-latest
        steps:
            - name: Checkout to main
              uses: actions/checkout@v7
            
            - name: Install XCBeautify and SwiftLint
              run: brew install xcbeautify swiftlint
              
            - name: Lint
              run: swiftlint lint
              
            - name: Show project info
              run: |
                xcodebuild -version
                xcodebuild -project GHActions.xcodeproj -scheme GHActions -showdestinations

            - name: Run unit tests
              run: set -o pipefail && xcodebuild -project GHActions.xcodeproj -scheme GHActions -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest,arch=arm64' clean test | xcbeautify
